### ISSUE TITLE
JOSS Review. Repo Changes.

### ISSUE THREAD

**Issue by torressa** [sjvrijn/mf2#1]
According to my [review](https://github.com/openjournals/joss-reviews/issues/2049#issuecomment-595979532) and @sjvrijn  [response](https://github.com/openjournals/joss-reviews/issues/2049#issuecomment-596131480).

The following need work:

 - [x] The pip installation doesn't automatically install the required dependencies. (tested on a clean pyenv).
 - [x] Also, when trying to run `python3 tests/create_regression_data.py` I get `ImportError: attempted relative import with no known parent package`.
 - [x] I see there's a fair amount of duplicated code, particularly, the `artificialMultifidelity.py` and `borehole.py` (from codacy).
 - [x] Scalabiliy plot for implementations.
 - [x] (lf possible) I think if the [implementations](https://www.sfu.ca/~ssurjano/multi.html) are fairly well known in the field, a simple comparison could help convince people to use your package. It should be fairly easy if you have access to a matlab license.

_Originally posted by @torressa in https://github.com/openjournals/joss-reviews/issues/2049#issuecomment-595979532_
and 
_Originally posted by @torressa in https://github.com/openjournals/joss-reviews/issues/2049#issuecomment-598033119_

**Comment by torressa** [comment]
The installation doesn't atomatically install numpy.
I think maybe you need to release the changes to pypi first.
I did
```none
python3 -m venv env
. env/bin/activate
pip install mf2
```
and I get 
```none
Collecting mf2
  Downloading https://files.pythonhosted.org/packages/d0/43/5a6e4f2c33e36776eb3a7b7cab13cd045d84d9514c298d220bccbcc79088/mf2-2019.11.3-py3-none-any.whl
Installing collected packages: mf2
Successfully installed mf2-2019.11.3
```

**Comment by sjvrijn** [comment]
> I think maybe you need to release the changes to pypi first.
True, I've only updated the source, not yet the PyPI version
